### ISSUE TITLE
cmsplugin_filer_link wrong data in editor

### ISSUE THREAD

**Issue by darbula** [divio/cmsplugin-filer#178] opened 2015-03-13 11:11 UTC
This bug is very easy to reproduce:

1. In text editor write `link1`, select and add new *CMSPlugin > Filer Link* let it link to `www.foo.com`

2. Add new paragraph, write `link2`, select and add new *CMSPlugin > Filer Link* and let it link to `www.bar.com`

3. Double click `link1` and editor is populated with Name: `link2` and Url `www.foo.com`.

This is not so big of a problem but in combination with #179 it becomes unsolvable.

This is tested on clean django cms project with following versions of relevant applications:

```
Django==1.6.10
cmsplugin-filer==0.10.1
django-cms==3.0.12
django-filer==0.9.9
djangocms-text-ckeditor==2.4.3
```

**Comment by mkoistinen** [comment] 2016-07-05 18:17
Confirmed. This is also an issue with "CMS Plugin Text CKEditor". However, there is a work-around. Save the plugin and re-open to edit link1 or link2 correctly. It seems to be related to unsaved Text plugins.

See: https://github.com/divio/djangocms-text-ckeditor/issues/331

Closing here.

**Closed by mkoistinen** 2016-07-05 18:17 UTC
